#!/bin/sh

sed -i "s/api_client_id=\"\"/api_client_id=\"${OD_API_ID}\"/g" /usr/local/etc/OneDrive/onedrive.cfg
sed -i "s/api_client_secret=\"\"/api_client_secret=\"${OD_API_SECRET}\"/g" /usr/local/etc/OneDrive/onedrive.cfg

if [ "${OD_API_URL}" ]
then
sed -i "s/https:\/\/onedrive.live.com\/about\/business\//${OD_API_URL}/g" /usr/local/etc/OneDrive/onedrive.cfg
echo "${OD_REFRESH_TOKEN}" > /usr/local/etc/OneDrive/.refresh_token
fi

if [ "${RCLONE_CONFIG}" ]
then
wget -O ~/.config/rclone/rclone.conf ${RCLONE_CONFIG}
fi

cd $GOPATH/src/github.com/lukasmartinelli/nigit && sed -i "s/8000/$PORT/g" nigit.go && go generate && go build && mv nigit $GOPATH/bin
cd /dl

nigit dl.sh cmd.sh
